FROM eclipse-temurin:24-jdk
RUN mkdir /app
WORKDIR /app

COPY target/*.jar app.jar

ENV SPRING_PROFILES_ACTIVE=prod
ENV SERVER_PORT=8081
ENV DATABASE_HOST=
ENV DATABASE_PORT=3306
ENV DATABASE_NAME=PAINEL_ADMINISTRATIVO
ENV DATABASE_USERNAME=
ENV DATABASE_PASSWORD=
ENV JWT_SECRET_KEY=
ENV FILE_UPLOAD_DIR=
ENV EMAIL_USER=
ENV EMAIL_PASSWORD=
ENV EMAIL_SETOR_RESPONSAVEL=
EXPOSE ${SERVER_PORT}

CMD ["java","-jar", "/app/app.jar"]