name: CI

on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Ensure UTF-8 encoding for properties
        run: |
          echo "Converting application-prod.properties to UTF-8 if needed..."
          iconv -f ISO-8859-1 -t UTF-8 src/main/resources/application-prod.properties -o src/main/resources/application-prod.properties || true

      - name: Build JAR with Maven
        run: mvn -B clean package -DskipTests

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install go-semantic-release
        run: go install github.com/go-semantic-release/semantic-release/v2/cmd/semantic-release@latest

      - name: Run semantic-release
        id: semrel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release --provider github --no-ci --version-file .version

      - name: Read generated version
        id: version
        run: |
          VERSION=$(cat .version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            oswaldo574/painel_administrativo_norteautopecas_backend:${{ steps.version.outputs.version }}
            oswaldo574/painel_administrativo_norteautopecas_backend:latest
